---
booktitle: Proceedings of the Workshop on Automatic Machine Learning
volume: 64
year: '2016'
published: 2016-12-04
start: 2016-06-24
end: 2016-06-24
shortname: AutoML
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: AutoML-2016
month: 0
cycles: false
editor:
- given: Frank
  family: Hutter
- given: Lars
  family: Kotthoff
- given: Joaquin
  family: Vanschoren
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Workshop on Automatic Machine Learning
    Held in New York, New York, USA on 24 June 2016

  Published as Volume 64 by the Proceedings of Machine Learning Research on 04 December 2016.

  Volume Edited by:
    Frank Hutter
    Lars Kotthoff
    Joaquin Vanschoren

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 24 Jun
url: http://proceedings.mlr.press
baseurl: "/v64"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
plugins:
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v64
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Workshop on Automatic Machine Learning
  url: https://sites.google.com/site/automl2016/
  location: New York, New York, USA
  dates:
  - 2016-06-24
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
